apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nwaku-railgun.configMapName" . }}
  labels:
    {{- include "nwaku-railgun.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- $staticNodes := concat .Values.config.network.additionalStaticNodes .Values.config.network.staticNodes }}
    rln-relay={{ .Values.config.rlnRelay.enabled }}
    rln-relay-dynamic={{ .Values.config.rlnRelay.dynamic }}
    rln-relay-eth-client-address={{ .Values.config.rlnRelay.ethClientAddress | toJson }}
    rln-relay-cred-path={{ .Values.config.rlnRelay.credPath | quote }}
    rln-relay-user-message-limit={{ .Values.config.rlnRelay.userMessageLimit }}
    rln-relay-eth-contract-address={{ .Values.config.rlnRelay.ethContractAddress | quote }}
    rln-relay-chain-id={{ .Values.config.rlnRelay.chainId }}
    rln-relay-epoch-sec={{ .Values.config.rlnRelay.epochSec }}

    relay={{ .Values.config.relay }}
    store={{ .Values.config.store }}
    store-message-db-url={{ .Values.config.storeMessageDbUrl | quote }}
    filter={{ .Values.config.filter }}
    lightpush={{ .Values.config.lightpush }}
    relay-peer-exchange={{ .Values.config.relayPeerExchange }}
    relay-service-ratio={{ .Values.config.relayServiceRatio | quote }}

    rendezvous={{ .Values.config.rendezvous }}

    rest={{ .Values.config.rest.enabled }}
    rest-address={{ .Values.config.rest.address | quote }}
    rest-port={{ .Values.service.rpc.port }}
    rest-admin={{ .Values.config.rest.admin }}
    rest-relay-cache-capacity={{ .Values.config.rest.relayCacheCapacity }}
    keep-alive={{ .Values.config.keepAlive }}

    cluster-id={{ .Values.config.network.clusterId }}
    num-shards-in-network={{ .Values.config.network.numShardsInNetwork }}
    shard={{ .Values.config.network.shards | toJson }}
    {{- if gt (len .Values.config.network.dnsAddrsNameServers) 0 }}
    dns-addrs-name-server={{ .Values.config.network.dnsAddrsNameServers | toJson }}
    {{- end }}

    staticnode={{ $staticNodes | toJson }}

    dns-discovery-url={{ .Values.config.network.dnsDiscoveryUrl | quote }}
    discv5-discovery={{ .Values.config.network.discv5Discovery }}
    {{- if .Values.config.network.nat.enabled }}
    nat={{ printf "extip:%s" .Values.config.network.nat.extIp | quote }}
    {{- end }}

    tcp-port={{ .Values.service.p2p.libp2p.port }}
    {{- if .Values.config.network.advertise.enabled }}
    ext-multiaddr={{ .Values.config.network.advertise.extMultiaddrs | toJson }}
    ext-multiaddr-only={{ .Values.config.network.advertise.extMultiaddrOnly }}
    {{- end }}
    discv5-udp-port={{ .Values.service.p2p.discv5.port }}
    websocket-port={{ .Values.service.websocket.port }}
    websocket-support={{ .Values.config.websocketSupport }}

    max-msg-size={{ .Values.config.maxMsgSize | quote }}
    filter-subscription-timeout={{ .Values.config.filterSubscriptionTimeout }}
    filter-max-peers-to-serve={{ .Values.config.filterMaxPeersToServe }}
    peer-store-capacity={{ .Values.config.peerStoreCapacity }}
    max-connections={{ .Values.config.maxConnections }}
    ip-colocation-limit={{ .Values.config.ipColocationLimit }}
    peer-persistence={{ .Values.config.peerPersistence }}
    peer-exchange={{ .Values.config.peerExchange }}
