{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nwaku-railgun.secretName" . }}
  labels:
    {{- include "nwaku-railgun.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.nodekey }}: {{ .Values.secrets.data.nodekey | quote }}
  {{- if .Values.config.rlnRelay.enabled }}
  {{ .Values.secrets.keys.rlnRelayCredPassword }}: {{ .Values.secrets.data.rlnRelayCredPassword | quote }}
  {{ .Values.secrets.keys.keystore }}: |
{{ .Values.secrets.data.keystore | indent 4 }}
  {{- end }}
{{- end }}
