{{- if .Values.service.rpc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nwaku-railgun.rpcServiceName" . }}
  labels:
    {{- include "nwaku-railgun.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.rpc.type }}
  selector:
    {{- include "nwaku-railgun.selectorLabels" . | nindent 4 }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpc.port }}
      targetPort: rpc
      protocol: TCP
{{- end }}
