secrets:
  existingSecret: nwaku-secrets

service:
  p2p:
    enabled: true
    type: NodePort

ingress:
  websocket:
    enabled: true
    className: traefik
    host: waku.example.com
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.tls.certresolver: le-http
    tls:
      enabled: true
      secretName: waku-websocket-tls
